#dotnet test ./test/JornadaMilhas.Unit.Test
#dotnet test ./test/JornadaMilhas.Integration.Test.API
#dotnet publish ./src/JornadaMilhas.API
name: Pipeline
on:
 push:
  branches: ["main"]
jobs:
  build:
   name: Minha primeira pipeline  
   runs-on: ubuntu-latest
   services:
    mssql:
      image: mcr.microsoft.com/mssql/server:2022-latest
      env:
        ACCEPT_EULA: "Y"
      ports:
        - 1433:1433
   steps:     
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      - name: Checkout do código
        uses: actions/checkout@v2      
       #dotnet test ./test/JornadaMilhas.Unit.Test
      - name: Execução do teste de unidade 
        run: dotnet test ./test/JornadaMilhas.Unit.Test
       #dotnet test ./test/JornadaMilhas.Integration.Test.API
      - name: Testes Integração
        run: dotnet test ./test/JornadaMilhas.Integration.Test.API 
       #dotnet publish ./src/JornadaMilhas.API
      - name: Publicando a API
        run: dotnet publish ./src/JornadaMilhas.API
  #env: 
  #  TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"
  #  TESTCONTAINERS_RYUK_DISABLED: "true"
    